stages:
    - dockerize

buildDockerRasa:
    stage: dockerize
    rules:
        - if: $CI_COMMIT_BRANCH == "dev"
        - if: $CI_COMMIT_BRANCH == "dev-dauren"
        - if: $CI_COMMIT_BRANCH == "qa"
        - if: $CI_COMMIT_BRANCH == "prod"
    image:
        name: gcr.io/kaniko-project/executor:v1.5.1-debug
        entrypoint:
            - ''
    script:
        - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}"
          > /kaniko/.docker/config.json
        - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile
          --cache --destination "$CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH/rasa:$CI_COMMIT_SHA"

buildDockerRasaSdk:
    stage: dockerize
    rules:
        - if: $CI_COMMIT_BRANCH == "dev"
        - if: $CI_COMMIT_BRANCH == "dev-dauren"
        - if: $CI_COMMIT_BRANCH == "qa"
        - if: $CI_COMMIT_BRANCH == "prod"
    image:
        name: gcr.io/kaniko-project/executor:v1.5.1-debug
        entrypoint:
            - ''
    script:
        - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}"
          > /kaniko/.docker/config.json
        - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/rasa-actions.dockerfile
          --cache --destination "$CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH/rasa-sdk:$CI_COMMIT_SHA"

buildDockerScoring:
    stage: dockerize
    rules:
        - if: $CI_COMMIT_BRANCH == "dev"
        - if: $CI_COMMIT_BRANCH == "dev-dauren"
        - if: $CI_COMMIT_BRANCH == "qa"
        - if: $CI_COMMIT_BRANCH == "prod"
    image:
        name: gcr.io/kaniko-project/executor:v1.5.1-debug
        entrypoint:
            - ''
    script:
        - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}"
          > /kaniko/.docker/config.json
        - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/scripts/scoring/Dockerfile
          --cache --destination "$CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH/scoring:$CI_COMMIT_SHA"
