stages:
    - dockerize
    - deploy

buildDocker:
    stage: dockerize
    rules:
        - if: $CI_COMMIT_BRANCH == "dev"
        - if: $CI_COMMIT_BRANCH == "qa"
        - if: $CI_COMMIT_BRANCH == "prod"
    image:
        name: gcr.io/kaniko-project/executor:v1.5.1-debug
        entrypoint:
            - ''
    script:
        - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}"
          > /kaniko/.docker/config.json
        - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile
          --cache --destination "$CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH:$CI_COMMIT_SHA"

#deployDevDocker:
#    stage: dockerize
#    rules:
#        - if: $CI_COMMIT_BRANCH == "dev"
#    image:
#        name: 
#    script:
#       -
