stages:
    - dockerize
    - deploy

buildDocker:
    stage: dockerize
    rules:
        - if: $CI_COMMIT_BRANCH == "dev"
        - if: $CI_COMMIT_BRANCH == "qa"
        - if: $CI_COMMIT_BRANCH == "prod"
    image:
        name: gcr.io/kaniko-project/executor:v1.5.1-debug
        entrypoint:
            - ''
    script:
        - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}"
          > /kaniko/.docker/config.json
        - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile
          --cache --destination "$CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH:$CI_COMMIT_SHA"


deployDevDocker:
   stage: deploy
   rules:
       - if: $CI_COMMIT_BRANCH == "dev"
   image:
       name: git.eduworks.us:5050/infrastructure/build-images/git:2.30.1-2
   script:
     - mkdir -p ~/.ssh
     - chmod 600 "$PRIVATE_KEY"
     - eval "$(ssh-agent -s)"
     - ssh-add "$PRIVATE_KEY" > /dev/null
     - mv "$DEV_KNOWN_HOSTS" ~/.ssh/known_hosts
     - ssh devdeployment@dev.ask.chat.eduworks.com "export IMAGE_TAG=$CI_COMMIT_SHA && envsubst < '/etc/rasaAaron/docker-compose.override.template' > '/etc/rasaAaron/docker-compose.override.yml'"
