version: "3.9"
services:
  rasa:
    build:
      context: .
    container_name: rasa
    environment:
      ACTION_ENDPOINT: http://rasa-actions:5055/webhook
      TOKENIZERS_PARALLELISM: 'false'
    ports:
      - "5005:5005"
    #command: ["run","--enable-api", "--cors", "*"]
  rasa-actions:
    build:
      context: .
      dockerfile: rasa-actions.dockerfile
    container_name: rasa-actions
    extra_hosts:
    - "host.docker.internal:host-gateway"
    environment:
      TFHUB_CACHE_DIR: /var/tmp/models
      TF_CPP_MIN_LOG_LEVEL: 3
      TOKENIZERS_PARALLELISM: 'false'
      ELASTIC_USERNAME: ${ES_USERNAME}
      ELASTIC_PASSWORD: ${ES_PASSWORD}
      ES_HOST: ${ES_HOST}