version: "3.9"
services:
  rasa:
    build:
      context: .
    container_name: rasa
    ports:
      - "5005:5005"
    command: ["run", "--cors", "*"]
  rasa-actions:
    build:
      context: .
      dockerfile: rasa-actions.dockerfile
    container_name: rasa-actions