# ES host
host: "http://localhost:9200/"

# Universal Sentence Encoder link in TF Hub
tfhub-embdedding-url: "https://tfhub.dev/google/universal-sentence-encoder/4"
tfhub-cache-dir: ""

# Index name for Askextension data
askextension-index: "askextension"
# Index mapping
askextension-mapping: >
  {
    "settings": {
      "number_of_shards": 1
    },
    "mappings": {
      "properties": {
        "faq-id"    : {"type": "integer"},
        "ticket-no" : {"type": "text"},
        "url"       : {"type": "text"},
        "created"   : {"type": "text"},
        "updated"   : {"type": "text"},
        "state"     : {"type": "text"},
        "county"    : {"type": "text"},
        "title"     : {"type": "text"},
        "question"  : {"type": "text"},
        "title-question"        : {"type": "text"},
        "title-question-vector" : {"type": "dense_vector", "dims": 512},
        "answer"    : {"type": "text"}
      }
    }
  }


