debugMode: "false"
# nginx specific settings
nginx:
  service:
    type: LoadBalancer
    port: 8001
    # hostname -I
    #externalIPs: [10.1.100.167]
    externalIPs: [192.168.1.7]
app:
    # microk8s build-in registry
    name: "localhost:32000/askchatbot-action-server"
    tag: "0.0.2"
# rasax specific settings
rasax:
    # initialUser is the user which is created upon the initial start of Rasa X
    initialUser:
        # password for the Rasa X user
        password: "eduworks"
    # passwordSalt Rasa X uses to salt the user passwords
    passwordSalt: "pw02"
    # token Rasa X accepts as authentication token from other Rasa services
    token: "pw03"
    # jwtSecret which is used to sign the jwtTokens of the users
    jwtSecret: "pw04"
    # rasa x version to deploy
    tag: "0.30.1"
# rasa: Settings common for all Rasa containers
rasa:
    # token Rasa accepts as authentication token from other Rasa services
    token: "pw05"
    # rasa open source version to deploy
    tag: "1.10.7-full"
# RabbitMQ specific settings
rabbitmq:
    # rabbitmq settings of the subchart
    rabbitmq:
        # password which is used for the authentication
        password: "pw06"
# global settings of the used subcharts
global:
    # postgresql: global settings of the postgresql subchart
    postgresql:
        # postgresqlPassword is the password which is used when the postgresqlUsername equals "postgres"
        postgresqlPassword: "pw07"
    # redis: global settings of the postgresql subchart
    redis:
        # password to use in case there no external secret was provided
        password: "pw08"
