version: '3.9'
services:
  chatbot-scoring:
    image: python:3.9-slim-bullseye
    container_name: chatbot-scoring
    volumes:
      - ./:/scoring/
    working_dir: /scoring/
    environment:
      PATH_DATA: ${PATH_DATA}
      RASA_URL: ${RASA_URL}
      STAGE: ${STAGE}
    tty: true
    command: >
      bash -c "apt-get update 
      && pip install --upgrade -r requirements.txt
      && python run_scoring.py"
#      && tail -f /dev/null"