version: '3.9'
services:
  scoring:
    build:
      context: .
      dockerfile: Dockerfile
    image: git.eduworks.us:5050/ask-extension/askchatbot/dev:0.0.1
    container_name: scoring
    environment:
      DATA_VALID: valid_questions.pkl
      DATA_NA: na_questions.pkl
      RASA_URL: https://dev.api.chat.ask.eduworks.com/webhooks/rest/webhook
      DESCRIPTION: Running experiment on prod
      MLFLOW_EXPERIMENT_NAME: chatbot_scoring
      MLFLOW_TRACKING_URI: https://ask.ml.eduworks.com
      MLFLOW_TRACKING_USERNAME: 
      MLFLOW_TRACKING_PASSWORD: 